### ISSUE TITLE
请问出现该错误怎么办

### ISSUE THREAD

**Issue by kafuuchino-s** [foxofice/sub_share#1]
![image](https://user-images.githubusercontent.com/51790568/59556307-d03c9680-8ff2-11e9-8661-7de6d0c1dbb3.png)
如题，下载数据库文件后就这样了

**Comment by foxofice** [comment]
并没发现你所说的情况，重新下载试试？

**Comment by 66568869** [comment]
把程序关闭 强制结束后 先用本地的更新一下 再用服务器更新

**Comment by asdf1319964f** [comment]
程序报错 win10 缺少根元素

**Comment by foxofice** [comment]
> 程序报错 win10 缺少根元素

有没有截图？

**Comment by kafuuchino-s** [comment]
我过了好久再来下载看看，发现已经没有这个问题了，中间我重装过系统。试试安装一下3dm离线运行库[https://dl.3dmgame.com/patch/89066.html](url)
