### ISSUE TITLE
是否统一使用 style link 调用“思源黑体 Bold” 以兼容思源黑体 v2.000+

### ISSUE THREAD

**Issue by sommio** [foxofice/sub_share#23]
思源黑体在 v2.000 后[删除了通过 family 调用其基本样式](https://github.com/adobe-fonts/source-han-sans/issues/394#issuecomment-1463236120)（Regular, Italic, Bold, Bold Italic）的支持，仅支持 style link 调用

在 v4+ Styles 需要在字段 Bold 中指定 -1 使用
```
Before:
Style: Default,思源黑体 CN Bold,48,&H,&H,&H,&H, 0
Style: Default,思源黑体 CN Bold,48,&H,&H,&H,&H,-1
```
```
After:
Style: Default,思源黑体 CN,48,&H,&H,&H,&H,-1
```

如果在 Events 中，则 `\fn思源黑体 CN Bold -> \b1\fn思源黑体 CN`

**Comment by foxofice** [comment]
adobe这种字体乱改的问题，通常有3种做法：
1、以后不再用思源黑体，也不帮各字幕组或手抄的擦屁股，直接摆烂
2、以后不再用思源黑体，顺便帮字幕组或手抄擦屁股，但是不知道会不会被出处指责乱改
3、继续用思源黑体，但是改一下style。但是以后adobe又作什么死又得改一遍

我个人建议是1，直接摆烂。当然如果你要是有空的话，采取第3个方案也是可以。不知道还有没有其他解决方案。
