### ISSUE TITLE
git clone 库在最终阶段报错

### ISSUE THREAD

**Issue by Karanoyo** [foxofice/sub_share#38]
## 报错信息：
`
$ git clone https://github.com/foxofice/sub_share.git
Cloning into 'sub_share'...
remote: Enumerating objects: 114630, done.
remote: Counting objects: 100% (3219/3219), done.
remote: Compressing objects: 100% (2052/2052), done.
remote: Total 114630 (delta 1149), reused 3186 (delta 1149), pack-reused 111411
Receiving objects: 100% (114630/114630), 1.83 GiB | 5.49 MiB/s, done.
Resolving deltas: 100% (44082/44082), done.
error: invalid path 'subs_list/animation/2017/(2017.10.6)结城友奈是勇者 -鹫尾须美之章-\-勇者之章-（第二季）/BD/DHR/joker2000, 聖天使黒猫 简化/Part1 鹫尾须美之章/01【わしおすみ(鹫尾须美)】.ass'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`
## 尝试解决：
`git-restore--source=HEAD:/`

虽然用了 git-restore--source=HEAD:/ 克隆成功了，
但是我在本地尝试搜索报错文件 “结城友奈是勇者 -鹫尾须美之章-\-勇者之章-（第二季）”，却始终无法找到。
可是在 github 上是可以搜索到的，缺少文件真受不了！
问了必应AI一整天，好不容易才找到挂上代理再克隆库的方法，结果还是报错了。

我看了一下报错信息 “鹫尾须美之章-\-勇者之章-（第二季）”，发现文件夹名中带有一个英文的反斜杠 \，
一般文件(夹)名是无法包含此类特殊符号的对吧。
克隆库时所有的文件好像都会下载到本地，因为Windows系统不支持这种命名，所以才出错的吗？
第一次折腾这些Git克隆命令，不想以失败告终，诚心寻求解决方法。

半夜看到报错哭死...

**Comment by dyphire** [comment]
Windows系统不支持一些特殊字符，该官方名称碰撞了这一限制
我能想到解决方案的解决方案是重命名`(2017.10.6)结城友奈是勇者 -鹫尾须美之章-\-勇者之章-（第二季）`为`(2017.10.6)结城友奈是勇者（第二季）`，@sommio

**Comment by foxofice** [comment]
结城友奈是勇者 -鹫尾须美之章-&-勇者之章- 已回档，可以正常检出了

**Comment by Karanoyo** [comment]
感谢各位！终于可以愉快的看番了

**Comment by sommio** [comment]
> Windows系统上的文件名不支持一些特殊字符，该官方名称碰撞了这一限制 我能想到的解决方案是重命名`(2017.10.6)结城友奈是勇者 -鹫尾须美之章-\-勇者之章-（第二季）`为`(2017.10.6)结城友奈是勇者（第二季）`，@sommio

并不是官方名称，官方把这两个分开的，集数都是独立的
完全是为了配合 bangumi，bangumi 用的是“结城友奈是勇者 -鹫尾须美之章-/-勇者之章-”，因为 github 不支持和我本地系统不支持斜杠作为文件名就自作聪明换成了反斜杠...

为了避免后来补番者混来我最终选择了 [bangumi 名称]（第二季）

其它网站的话：
中日维基：跟 Bangumi 一样是“結城友奈は勇者である -鷲尾須美の章-/-勇者の章-”
英语维基：合并为 Season 2
動畫瘋：合并为第二季（願望清單）
[AMZN](https://www.amazon.com/gp/video/detail/B07663FM16)：合并为 Season 2
[Hidve](https://www.hidive.com/tv/yuki-yuna-is-a-hero-the-hero-chapter)： 拆分为两章
MAL/ANL：跟 Hidive 一样拆分为两章

**Comment by foxofice** [comment]
> 遇到Win下的各种无法作为名称的字符，建议改成全角字符，比如 : -> ：、/ -> ／、? -> ？等
