### ISSUE TITLE
如何处理字幕组魔改字体？

### ISSUE THREAD

**Issue by sommio** [foxofice/sub_share#41]
在我最近提交的“[赞州中学勇者部] 结城友奈是勇者 -大满开之章- ”字幕中发现了大量魔改字体
7z@LZMA 参数拉满压出来的大小是 69MiB，如果要上传的话得分成两个 part

这类魔改字体的特征是
- 只用一部番
- 在互联网上难以寻找

```
5.3M TaishaGothic-Bold.otf
5.3M TaishaGothic-DemiBold.otf
5.3M TaishaGothic-ExtraBold.otf
5.3M TaishaGothic-Heavy.otf
5.4M TaishaGothic-Regular.otf
5.3M TaishaGothic-SemiBold.otf
5.3M TaishaGothicRotated-Bold.otf
9.1M TaishaMaru-Bold.otf
9.2M TaishaMaru-DemiBold.otf
9.3M TaishaMaru-Regular.otf
9.2M TaishaMincho-Bold.otf
9.5M TaishaMincho-DemiBold.otf
9.6M TaishaMinchoRotated-DemiBold.otf
9.5M TaishaMinchoRotated-Regular.otf
9.6M TaishaMinchoRotated-SemiBold.otf
72M  魔改字体.7z
```

可能对应原始字体，其中 Rotated 为魔改竖排：
```
TaishaGothic -> 方正兰亭黑
TaishaMaru   -> 方正兰亭圆
TaishaMincho -> 方正*雅宋
```

压缩参数能拉满的我都拉满了
`7z a -t7z -mx=9 -mfb=273 -ms -myx=9 -mtm=- -mmt -mmtf -md=1536m -mmf=bt3 -mmc=10000 -mpb=0 -mlc=0 -m0=lzma -mtc -mta -mt`

**Comment by dyphire** [comment]
不建议上传字体包，可以选择上传云盘放入字体链接的方式处理
魔改字体可以还原原本字体的我是推荐进行处理的
PS：我对字幕组使用某些魔改字体的行为不是很感冒，很多魔改字体的质量并不高还会给使用者带来困扰。什么狮尾四季春，还有霞鹜文楷作者开发的一系列魔改字体之类

**Comment by sommio** [comment]
我只考虑获取难度，像“超研澤中特圓”的原始字体“[文鼎中特圓/文媛中特圓/文鼎圓體 EB](https://ifontcloud.com/index/images/newknowledge/20220328/%E6%96%87%E9%BC%8E%E6%96%B0%E8%88%8A%E5%AD%97%E5%9E%8B%E5%90%8D%E7%A8%B1%E5%B0%8D%E7%85%A7%E8%A1%A820220328.pdf)”要比魔改字体更难获取
