### ISSUE TITLE
git克隆或推送仓库时长路径报错的解决方法

### ISSUE THREAD

**Issue by dyphire** [foxofice/sub_share#43]
由于操作系统对于长路径的字符限制会导致在git克隆或推送仓库时出现报错无法继续执行的问题，可以通过以下命令来解除git的长路径的限制：
```bash
git config --global core.longpaths true
```
Windows上还需要进一步执行以下命令：
```bash
git config --global core.protectNTFS false
```

**Comment by sommio** [comment]
这个方法仅适用于 Windows，它是 [MSYS](https://github.com/msysgit/git/pull/110) 的限制
对于 Linux 来说，它是[内核硬编码](https://github.com/torvalds/linux/blob/0c7030038e6106711c5d0b237c980905dd3244ec/include/uapi/linux/btrfs_tree.h#L22)的

**Comment by dyphire** [comment]
原来Linux上还存在硬编码的字符限制，不通用的解决方法就没有意义了，感谢告知

**Comment by foxofice** [comment]
> 原来Linux上还存在硬编码的字符限制，不通用的解决方法就没有意义了，感谢告知

之前有两个提交，暂时删除了过长的目录，一个是白箱、一个是寒蝉，你那边把目录修改得短一点再重新添加一下。比如vcb的就总是很长，一般直接写成“vcb”大家也能看懂。

**Comment by dyphire** [comment]
> > 原来Linux上还存在硬编码的字符限制，不通用的解决方法就没有意义了，感谢告知
> 
> 之前有两个提交，暂时删除了过长的目录，一个是白箱、一个是寒蝉，你那边把目录修改得短一点再重新添加一下。比如vcb的就总是很长，一般直接写成“vcb”大家也能看懂。

重新处理添加了，奇怪的是db.xml在github上的diff和本地显示的不一样，出现了大量改变项

**Comment by foxofice** [comment]
> 

每次更新后，需要运行软件按F5更新db.xml
