### ISSUE TITLE
恋爱小行星缺失6.5集字幕(附完整字幕)

### ISSUE THREAD

**Issue by PlayerYao** [foxofice/sub_share#6]
我看本项目恋爱小行星目录下有[Airota&LoliHouse] 的字幕 但是缺失了6.5集的字幕

找到一份全的,希望补充上去

P.S. Q群倒了吗

[[Airota&LoliHouse] Koisuru Asteroid [BDRip][v2].zip](https://github.com/foxofice/sub_share/files/6592595/Airota.LoliHouse.Koisuru.Asteroid.BDRip.v2.zip)

**Comment by LianXia233** [comment]
有空了我补一下，q群还在的

**Comment by LianXia233** [comment]
已更新
