### ISSUE TITLE
第一次用这东西，想请教一下@@

### ISSUE THREAD

**Issue by RedComet2021** [foxofice/sub_share#7]
不好意思，我找了好久都找不到类似 “下载raw数据” 这样的按键，能麻烦大大指教一下吗？谢谢~

**Comment by RedComet2021** [comment]
![image](https://user-images.githubusercontent.com/85382266/120882428-79c72900-c60a-11eb-8bad-3f999d2caeed.png)

**Comment by RedComet2021** [comment]
我想先试单下载这个字幕就好了，谢谢~

**Comment by LianXia233** [comment]
在网页上鼠标选中你想要下载的字幕，然后点击右键使用下载器进行下载
![](https://cdnimg.acgget.com/images/202106/67fb77e320cb4a0a.png)
![](https://cdnimg.acgget.com/images/202106/ba7befceef4f43d7.png)

**Comment by li-guohao** [comment]
可以搭配这个插件下载Github目录
https://chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn
