### ISSUE TITLE
字幕轴错误：“(2021.3.8)新・福音战士剧场版：终”，两版字幕字幕轴都有误差

### ISSUE THREAD

**Issue by LSP0123** [foxofice/sub_share#94]
平台：windows11 23H2 
播放器：mpv-lazy-20231101 默认设置

视频源：[LoliHouse] EVANGELION 3.0+1.11 THRICE UPON A TIME [BDRip 1920x814 HEVC-10bit FLAC].mkv
torrent hash：63b2fc21a1be76d0a7d793e7c8a72a87ba5c96df

示例：
Dialogue: 0,`2:23:20.20`,2:23:21.20,CN,,0,0,0,,玛丽小姐！
字幕近似正确开始时间：`02:23:29:00`

**Comment by foxofice** [comment]
加了两个其他版本，如果还有问题的话可以考虑下自己调轴

**Comment by dyphire** [comment]
针对这个问题需要测试复现，确认是时轴还是播放设备问题

**Comment by LSP0123** [comment]
> 针对这个问题需要测试复现，确认是时轴还是播放设备问题

确认了下，这个确实是字幕轴的问题，应该是web版和BD版有区别
```
目前看到網路上有WEBrip(3.0+1.01)跟BDrip(3.0+1.11)，兩者雖然劇情沒變，但片長有差，所以WEB字幕不能直接給BD套用。
然後BDrip還分成「有片頭Logo版」跟「沒有片頭Logo版」，兩者片長又不同，但只要整片時間軸直接平移就了事。
```

提交的BD字幕和lolihouse的BDrip确实是可以对的上，可能需要再针对webrip的看一下，我已经在下载lolihouse的webrip来确认了
