### ISSUE TITLE
提一些小建议

### ISSUE THREAD

**Issue by Refrain69** [foxofice/sub_share#98]
外观方面：
1. net framework默认情况下在高分辨率屏幕上会模糊
2. 窗体字体最好改成微软雅黑

其他：
1. 可以把程序部分和数据库分成两个仓库，不然对于贡献者来说不太方便clone
2. 生成时，Files文件夹不会复制到生成目录下，还需手动复制

**Comment by Refrain69** [comment]
https://github.com/Refrain69/sub_db

**Comment by foxofice** [comment]
1、.net framework在高分辨率屏幕上不会模糊，出现模糊的话大概率是系统缩放的问题
2、窗体字体是由系统设置决定

程序部分可以考虑分离到一个新仓库中，下次有空再开个新仓库

**Comment by Refrain69** [comment]
好的。我也对程序部分进行了一些改进，见[https://github.com/Refrain69/sub_db](https://github.com/Refrain69/sub_db)
